apiVersion: v1

kind: Service

metadata:
  name: external-loadbalancer
  labels:
    app: external-loadbalancer
    tier: frontend

spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: external
    
