apiVersion: v1

kind: Service

metadata:
  name: internal-clusterip
  labels:
    app: internal-clusterip
    tier: backend

spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: internal
    